# General configuration
server:
  port: 8080
  servlet:
    context-path: /sql

spring:
   mvc:    async:      request-timeout: -1
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/myproj
     username: root
     password: onceas
     driverClassName: com.mysql.cj.jdbc.Driver
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
